# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 20:08
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergotechnologyAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Короткое имя')),
            ],
            options={
                'verbose_name': 'Энерготехнология все',
                'db_table': 'energotechnologyall',
                'verbose_name_plural': 'Энерготехнологии все',
            },
        ),
        migrations.CreateModel(
            name='EnergotechnologyEast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Короткое имя')),
            ],
            options={
                'verbose_name': 'Энерготехнология земля',
                'db_table': 'energotechnologyeast',
                'verbose_name_plural': 'Энерготехнологии земля',
            },
        ),
        migrations.CreateModel(
            name='EnergotechnologyOsveshenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Короткое имя')),
            ],
            options={
                'verbose_name': 'Энерготехнология освещение',
                'db_table': 'energotechnologyosveshenie',
                'verbose_name_plural': 'Энерготехнологии освещение',
            },
        ),
        migrations.CreateModel(
            name='EnergotechnologyOtoplenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Короткое имя')),
            ],
            options={
                'verbose_name': 'Энерготехнология отопление',
                'db_table': 'energotechnologyotoplenie',
                'verbose_name_plural': 'Энерготехнологии отопление',
            },
        ),
        migrations.CreateModel(
            name='EnergotechnologySun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Короткое имя')),
            ],
            options={
                'verbose_name': 'Энерготехнология солнце',
                'db_table': 'energotechnologysun',
                'verbose_name_plural': 'Энерготехнологии солнце',
            },
        ),
        migrations.CreateModel(
            name='EnergotechnologyWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Короткое имя')),
            ],
            options={
                'verbose_name': 'Энерготехнология вода',
                'db_table': 'energotechnologywater',
                'verbose_name_plural': 'Энерготехнологии вода',
            },
        ),
    ]
