# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 17:44
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textContact', ckeditor.fields.RichTextField(blank=True, verbose_name='Наши контакты')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='EnergotechnologyAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Короткое имя')),
            ],
            options={
                'verbose_name': 'Общая информация',
                'verbose_name_plural': 'Общая информация',
                'db_table': 'energotechnologyall',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'db_table': 'faq',
            },
        ),
        migrations.CreateModel(
            name='InfoText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoText', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, help_text='Информация на на странице информации', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Короткое имя')),
            ],
            options={
                'verbose_name': 'Информации',
                'verbose_name_plural': 'Информация',
                'db_table': 'infoText',
            },
        ),
        migrations.CreateModel(
            name='MainText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainText', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, help_text='Информация на главной странице', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Короткое имя')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
                'db_table': 'indextText',
            },
        ),
    ]
