# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energotechnologyall',
            options={'verbose_name': 'Общая информация', 'verbose_name_plural': 'Общая информация'},
        ),
        migrations.AlterModelOptions(
            name='energotechnologyeast',
            options={'verbose_name': 'Земля', 'verbose_name_plural': 'Земля'},
        ),
        migrations.AlterModelOptions(
            name='energotechnologyosveshenie',
            options={'verbose_name': 'Освещение', 'verbose_name_plural': 'Освещение'},
        ),
        migrations.AlterModelOptions(
            name='energotechnologyotoplenie',
            options={'verbose_name': 'Отопление', 'verbose_name_plural': 'Отопление'},
        ),
        migrations.AlterModelOptions(
            name='energotechnologysun',
            options={'verbose_name': 'Солнце', 'verbose_name_plural': 'Солнце'},
        ),
        migrations.AlterModelOptions(
            name='energotechnologywater',
            options={'verbose_name': 'Вода', 'verbose_name_plural': 'Вода'},
        ),
    ]
