# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 17:44
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staticpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergotechnologyEast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Короткое имя')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staticpages.EnergotechnologyAll', verbose_name='Энерготехнологии')),
            ],
            options={
                'verbose_name': 'Земля',
                'verbose_name_plural': 'Земля',
                'db_table': 'energotechnologyeast',
            },
        ),
        migrations.CreateModel(
            name='EnergotechnologyOsveshenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Короткое имя')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staticpages.EnergotechnologyAll', verbose_name='Энерготехнологии')),
            ],
            options={
                'verbose_name': 'Освещение',
                'verbose_name_plural': 'Освещение',
                'db_table': 'energotechnologyosveshenie',
            },
        ),
        migrations.CreateModel(
            name='EnergotechnologyOtoplenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Короткое имя')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staticpages.EnergotechnologyAll', verbose_name='Энерготехнологии')),
            ],
            options={
                'verbose_name': 'Отопление',
                'verbose_name_plural': 'Отопление',
                'db_table': 'energotechnologyotoplenie',
            },
        ),
        migrations.CreateModel(
            name='EnergotechnologySun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Короткое имя')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staticpages.EnergotechnologyAll', verbose_name='Энерготехнологии')),
            ],
            options={
                'verbose_name': 'Солнце',
                'verbose_name_plural': 'Солнце',
                'db_table': 'energotechnologysun',
            },
        ),
        migrations.CreateModel(
            name='EnergotechnologyWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Короткое имя')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staticpages.EnergotechnologyAll', verbose_name='Энерготехнологии')),
            ],
            options={
                'verbose_name': 'Вода',
                'verbose_name_plural': 'Вода',
                'db_table': 'energotechnologywater',
            },
        ),
    ]
