# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 15:48
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energotechnology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energotechnologyall',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='energotechnologyall',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Титул'),
        ),
    ]
