# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-11 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energotechnology', '0002_auto_20170327_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energotechnologyall',
            options={'verbose_name': 'Энерготехнологии', 'verbose_name_plural': 'Энерготехнологии'},
        ),
    ]
