# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textAnswer', models.CharField(max_length=100, verbose_name='Ответ')),
                ('valueAnswer', models.SmallIntegerField(verbose_name='количество ответов')),
            ],
            options={
                'verbose_name_plural': 'Ответы',
                'db_table': 'answer',
                'verbose_name': 'Ответ',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textQuestion', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('dateQuestion', models.DateField(verbose_name='Дата создания вопроса')),
            ],
            options={
                'verbose_name_plural': 'Вопросы',
                'db_table': 'question',
                'verbose_name': 'Вопрос',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Question', verbose_name='Относится к вопросу'),
        ),
    ]
