# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='valueAnswer',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='количество ответов'),
        ),
        migrations.AlterField(
            model_name='question',
            name='dateQuestion',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания вопроса'),
        ),
    ]
