# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 15:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_question_usersanswers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Титул')),
                ('textMain', ckeditor.fields.RichTextField(verbose_name='Заглавная страница')),
            ],
            options={
                'db_table': 'indextText',
                'verbose_name': 'Информация на главной странице',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('title', models.CharField(max_length=50, verbose_name='заголовок новости')),
                ('textNews', ckeditor.fields.RichTextField(verbose_name='Текст Новости')),
                ('imgNews', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
            ],
            options={
                'db_table': 'news',
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.SmallIntegerField(verbose_name='Рейтинг')),
                ('comment', models.TextField(verbose_name='Отзыв')),
                ('dateCreate', models.DateField(auto_now_add=True, verbose_name='Дата создания отзыва')),
            ],
            options={
                'db_table': 'testimonials',
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
    ]
