# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20170322_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='imgNews',
            field=models.ImageField(blank=True, default='/static/img/noimage.jpg', null=True, upload_to='static/media/images/', verbose_name='Картинка'),
        ),
    ]
