# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 17:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_maintext_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintext',
            options={'verbose_name': 'Информация на главной странице', 'verbose_name_plural': 'О нас'},
        ),
        migrations.RemoveField(
            model_name='maintext',
            name='textMain',
        ),
        migrations.AddField(
            model_name='maintext',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='maintext',
            name='title',
            field=models.CharField(blank=True, help_text='О нас', max_length=100),
        ),
    ]
