# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20170323_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='imgNews',
            field=models.ImageField(blank=True, default='images/noimage.jpg', null=True, upload_to='static/media/images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
