# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20170323_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Вопрос')),
            ],
            options={
                'verbose_name_plural': 'FAQ',
                'verbose_name': 'FAQ',
                'db_table': 'faq',
            },
        ),
    ]
