# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20170305_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintext',
            options={'verbose_name': 'Информация на главной странице', 'verbose_name_plural': 'Информация на главной странице'},
        ),
        migrations.RenameField(
            model_name='maintext',
            old_name='about',
            new_name='mainText',
        ),
        migrations.AlterField(
            model_name='maintext',
            name='title',
            field=models.CharField(blank=True, help_text='Информация на главной странице', max_length=100),
        ),
    ]
