# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20170305_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dateTime',
            field=models.DateField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
