# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 21:50
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textContact', ckeditor.fields.RichTextField(blank=True, verbose_name='Наши контакты')),
            ],
            options={
                'verbose_name': 'Контакт',
                'db_table': 'contact',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
    ]
