# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20170305_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='Активный опрос'),
        ),
        migrations.AlterField(
            model_name='news',
            name='imgNews',
            field=models.ImageField(blank=True, default='/img/noimage.jpg', null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
