# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20170306_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Голосование', 'verbose_name_plural': 'Голосование'},
        ),
        migrations.AddField(
            model_name='answer',
            name='persent',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
