# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 21:23
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20170309_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainText', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, help_text='Информация на на странице информации', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Короткое имя')),
            ],
            options={
                'verbose_name': 'Информация на на странице информации',
                'verbose_name_plural': 'Информация на на странице информации',
                'db_table': 'infoText',
            },
        ),
    ]
