# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_infotext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infotext',
            old_name='mainText',
            new_name='infoText',
        ),
    ]
