# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 22:15
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20170311_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintext',
            name='mainText',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст'),
        ),
    ]
